### ISSUE TITLE
FR_30_V01: User progress tracking section

### ISSUE THREAD

**Issue by ccarnus** [ccarnus/BrightMinds_beta#43]
In the track section:

- [x] Remove the track per category
- [x] Create a "cambere of the most watched categories
- [x] Create a gauge for the main objective tracking
- [x] display the streak here with a little more enhancement for it than in the profile section
- [x] Total cast watching
- [x] Total number of evaluations taken
- [x] Success rate for the evaluations
- [x] Progress made since beginning.
- [x] A spider chart of the progress in each category
